Личный проект: шаблонизируй это
htmlacademy-ecmascript/16780-big-trip-12 pull request #4
Opened 2020-08-14 14:13 UTC by aozubrilin

2020-08-14 17:10 UTC, balesniy commented on src/mock/event.js
> +const MAX_PRICE = 200;
посмотри на критерий https://up.htmlacademy.ru/ecmascript/12/criteries#b16

2020-08-14 17:12 UTC, balesniy commented on src/mock/event.js
> +  return new Array(countOffers).fill().map(() => OFFERS[getRandomInteger(0, OFFERS.length - 1)]);
опции привязаны к типу события, у каждого типа свой набор опций

2020-08-14 17:13 UTC, balesniy commented on src/mock/event.js
> +      description: generateDescription(),
описание и фото привязываются к городу, у точек в одном городе будет одинаковое описание

2020-08-14 17:14 UTC, balesniy commented on src/mock/event.js
> +  return new Array(countFoto).fill().map(() =>`<img class="event__photo" src="http://picsum.photos/248/152?r=${Math.random()}" alt="Event photo"></img>`).join(`\n`);
в данных нужно оставить только адрес, а разметку добавить в компоненте

2020-08-14 17:16 UTC, balesniy commented on src/utils.js
> +const addZero = (numb) => {
нас просят не использовать тип данных в названиях и не использовать сокращения. мы уже умеем шаблонные строки, так что лучше обойтись без конкатенаций, обрати внимание на метод https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String/padStart

2020-08-14 17:19 UTC, balesniy commented on src/utils.js
> +export const getRandomArrayItem = (arr) => {
https://up.htmlacademy.ru/ecmascript/12/criteries#b4 https://up.htmlacademy.ru/ecmascript/12/criteries#b9 для абстрактного массива можно использовать например items

2020-08-14 17:43 UTC, balesniy commented on src/view/edit-event.js
> +    + typeItems.map((item) => `<div class="event__type-${item.toLowerCase()}">
конкатенация в шаблонных строках не нужна - https://up.htmlacademy.ru/ecmascript/12/criteries#b33, и вложенные map плохо читаются, лучше вынести в функцию

2020-08-14 17:44 UTC, balesniy commented on src/view/edit-event.js
> +const createOffersTemplate = (Offers) => {
у нас lowerCamelCase, с заглавной именуем классы

2020-08-14 17:47 UTC, balesniy commented on src/view/event.js
> +  return offer !== null ? offer.slice(0, 3).map((offerItem) =>
сюда приходит массив опций, он может быть пустым, но всегда массив. волшебные числа лучше сразу оформить в константы

2020-08-14 17:49 UTC, balesniy commented on src/view/filter.js
> +  for (const item of filter) {
лучше map+join очень уж на https://up.htmlacademy.ru/ecmascript/12/criteries#b33 похоже

2020-08-14 17:52 UTC, balesniy commented on src/view/trip-info.js
> +  if (events.length > 3) {
события могут быть в одном городе, задание просит "Если **городов** больше 3-х,"

2020-08-14 17:54 UTC, balesniy commented on src/view/trip-info.js
> +    if (index !== events.length - 1) {
нам нужно указать первый и последний город, они не обязательно идут подряд, нужно учесть длительность события

2020-08-14 17:55 UTC, balesniy commented on src/view/trip-info.js
> +  const dateEnd = getShortDate(events[events.length - 1].dateEnd);
последнее событие в списке не обязательно самое позднее)

2020-08-14 17:55 UTC, balesniy commented on src/view/trip-info.js
> +      return `${event.destination} &mdash; `;
еще нужно решить что мы будем показывать если 3 события произошли в одном городе

2020-08-19 16:15 UTC, balesniy requested changes
много замечаний осталось с прошлого ревью

2020-08-19 16:15 UTC, balesniy commented on src/mock/event.js
> +    destinationInfo: {
объект в массиве destinations уже содержит destinationInfo, повторный поиск данных избыточен

2020-08-19 16:15 UTC, balesniy commented on src/mock/offers.js
> +    offers: [
Данные должны генерироваться случайно — никакого ручного заполнения массивов.

2020-08-19 16:15 UTC, balesniy commented on src/utils.js
> +export const getRandomArrayItem = (arr) => {
🆙

2020-08-19 16:15 UTC, balesniy commented on src/view/edit-event.js
> +    + typeItems.map((item) => `<div class="event__type-${item.toLowerCase()}">
🆙

2020-08-19 16:15 UTC, balesniy commented on src/view/edit-event.js
> +  const OffersTemplate = createOffersTemplate(offers, type);
с заглавной называем только классы

2020-08-19 16:15 UTC, balesniy commented on src/view/event.js
> +  return offer !== null ? offer.slice(0, 3).map((offerItem) =>
🆙

2020-08-19 16:15 UTC, balesniy commented on src/view/filter.js
> +const createFiterItemsTemlate = (filter) => {
массивы просят называть во множественном числе

2020-08-19 16:15 UTC, balesniy commented on src/view/sort.js
> +  const icon = `<svg class="trip-sort__direction-icon" width="8" height="10" viewBox="0 0 8 10">
константы нужно оформить капсом и вынести из функции

2020-08-19 16:15 UTC, balesniy commented on src/view/trip-info.js
> +  if (destinations.length > 3 && uniqDestinations.length !== 1) {
магические числа нужно оформить в константы

2020-08-19 16:15 UTC, balesniy commented on src/view/trip-info.js
> +    return uniqDestinations;
uniqDestinations это массив, функция должна вернуть строку

2020-08-19 16:15 UTC, balesniy commented on src/view/trip-info.js
> +    if (index !== events.length - 1) {
🆙

2020-08-20 06:41 UTC, aozubrilin commented on src/view/trip-info.js
> +    if (index !== events.length - 1) {
Пока убрал вывод городов. Логика изначально была ,что события идут друг за другом и одновременно не может происходить 2 события. Одно закончилось, другое началось.  А так если количество городов 3 то надо учесть дату, при первом событий смотреть на дату начала, при последнем на дату окончания . А еще есть вариант что 3 события и 2 города.  Пока более менее красиво описать это не  выходит.  Просто ступр. Пока переключусь на другие задачи я и так уже сильно отстаю.

2020-08-20 11:11 UTC, balesniy requested changes
снова остались замечания с прошлого ревью, просмотри внимательно пожалуйста

2020-08-20 11:11 UTC, balesniy commented on src/mock/event.js
> +    if (it.city === destination) {
посмотри на критерий оптимальности цикла, возможно я не до конца понял твою идею, но вижу что цикл обходит весь массив городов, чтобы заполнить только один

2020-08-20 11:11 UTC, balesniy commented on src/mock/event.js
> +      it.destinationInfo.photos.map((photo) => photos.push(photo));
результат map не используется, возможно ты хотел сделать копию массива destinationInfo.photos, для этого удобно применить slice

2020-08-20 11:11 UTC, balesniy commented on src/mock/event.js
> +  let photos = [];
неизменяемые значения объявляем через const

2020-08-20 11:11 UTC, balesniy commented on src/mock/event.js
> +  let result = [];
неизменяемые значения объявляем через const

2020-08-20 11:11 UTC, balesniy commented on src/mock/event.js
> +    if (it.type === type) {
посмотри на критерий оптимальности цикла, обходим весь массив чтобы обработать один элемент. кроме того, результат map не используется

2020-08-20 11:11 UTC, balesniy commented on src/mock/event.js
> +  const maxDaysGap = 2;
🆙

2020-08-20 11:11 UTC, balesniy commented on src/mock/event.js
> +  return new Date(currentDate);
🆙

2020-08-20 11:11 UTC, balesniy commented on src/mock/event.js
> +    destinationInfo: {
🆙

2020-08-20 11:11 UTC, balesniy commented on src/view/trip-info.js
> +      <h1 class="trip-info__title">----</h1>
в задании просят убрать весь блок из разметки, если не заполнять его, напиши пока сюда что то наглядное, чтобы не забыть)

2020-08-20 11:56 UTC, aozubrilin commented on src/utils.js
> +export const getRandomArrayItem = (arr) => {
+

2020-08-20 12:00 UTC, aozubrilin commented on src/view/event.js
> +  return offer !== null ? offer.slice(0, 3).map((offerItem) =>
+++

2020-08-20 12:02 UTC, aozubrilin commented on src/mock/event.js
> +  let result = [];
+++

2020-08-20 12:03 UTC, aozubrilin commented on src/mock/event.js
> +  const maxDaysGap = 2;
+++

2020-08-20 12:04 UTC, aozubrilin commented on src/mock/event.js
> +  return new Date(currentDate);
+++

2020-08-20 12:11 UTC, aozubrilin commented on src/view/edit-event.js
> +  const OffersTemplate = createOffersTemplate(offers, type);
++++

2020-08-20 12:16 UTC, aozubrilin commented on src/view/filter.js
> +const createFiterItemsTemlate = (filter) => {
+++

2020-08-20 12:16 UTC, aozubrilin commented on src/view/sort.js
> +  const icon = `<svg class="trip-sort__direction-icon" width="8" height="10" viewBox="0 0 8 10">
++++

2020-08-20 12:57 UTC, aozubrilin commented on src/view/edit-event.js
> +    + typeItems.map((item) => `<div class="event__type-${item.toLowerCase()}">
+++

2020-08-20 16:14 UTC, aozubrilin commented on src/mock/event.js
> +    destinationInfo: {
+++

2020-08-20 16:14 UTC, aozubrilin commented on src/mock/offers.js
> +    offers: [
+++

2020-08-20 16:25 UTC, aozubrilin commented
1

2020-08-20 16:27 UTC, aozubrilin commented
Извиняюсь. Я не раскрыл все замечания. Затупил. Буду внимательней.

2020-08-20 20:30 UTC, balesniy approved these changes

2020-08-20 20:30 UTC, balesniy commented on src/mock/offers.js
> +   .map(() => Object.assign(MOK_OFFERS[getRandomInteger(0, MOK_OFFERS.length - 1)], {price: getRandomInteger(Price.MIN, Price.MAX)}));
чтобы не изменять исходный объект, можно первым параметром в Object.assign передать новый пустой объект

2020-08-20 20:30 UTC, balesniy commented on src/mock/offers.js
> +  for (const item of types) {
похоже на то как работает map )

2020-08-20 20:30 UTC, balesniy commented on src/view/edit-event.js
> +    ${item.offers.map((offer) => `<div class="event__offer-selector">
вложенные map плохо читаются, выноси их в отдельные функции

2020-08-20 20:30 UTC, balesniy commented on src/view/trip-info.js
> +      <h1 class="trip-info__title">@@@Chtobi Ne Zabil@@@</h1>
👍

2020-08-20 20:30 UTC, merged